# Generated by Django 4.2.27 on 2025-12-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('description',)},
        ),
    ]
